[env.development]
TARGET_PATH = "target/debug"

[env.production]
TARGET_PATH = "target/release"
BUILD_FLAGS = "--release"

[tasks.build-driver]
script = [
    "cargo b %BUILD_FLAGS%"
]

[tasks.rename]
ignore_errors = true
script = [
	"cd %TARGET_PATH%",
	"rename WojakNT.dll WojakNT.sys",
]

[tasks.sign]
dependencies = ["build-driver", "rename"]
script = [
	# Load the Visual Studio Developer environment
	"call \"%ProgramFiles%\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\"",

	# Create a self signed certificate (only if not already done)
	"if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer ) else ( echo Certificate already exists. )",

	# Sign the driver
	"signtool sign /fd SHA256 /a /v /s PrivateCertStore /n DriverCertificate /t http://timestamp.digicert.com %TARGET_PATH%/WojakNT.sys"
]
